### ISSUE TITLE
✨ Implement service-level retry budgets

### ISSUE THREAD

**Issue by roma-glushko** [roma-glushko/hyx#65]
The current retry component is based on the counting retries that happens on the scope of one request. 

It's useful to watch for a general amount of requests/retries we have done so far trying to communicate with given dependant mservice.

**Comment by Chris2W** [comment]
I can attempt to tackle this issue, if you're taking any contributions!

**Comment by roma-glushko** [comment]
Hey @Chris2W, certainly! I would appreciate any help ❤️ 
 
I was thinking of reusing the current token buckets that Hyx provides to limit number of retries. Take a look at this guy: https://github.com/roma-glushko/hyx/blob/main/hyx/ratelimit/managers.py#L12

**Comment by Chris2W** [comment]
Appreciate it! Sorta new to open source and wanted to dive into distributed systems. 

Would the following test be a somewhat valid usage of the retry decorator that limits the number of retries via the TokenBucketLimiter class from https://github.com/roma-glushko/hyx/blob/main/hyx/ratelimit/managers.py#L12 ?

`async def test__retry__global_retry_limit() -> None:
    listener = Listener()
    max_global_retries = 4
    per_time_secs = 1
    bucket_size = 4

    @retry(on=RuntimeError, max_global_retries=max_global_retries, per_time_secs=per_time_secs, bucket_size=bucket_size, listeners=(listener,))
    async def faulty_func() -> int:
        raise RuntimeError

    with pytest.raises(RateLimitExceeded):
        for _ in range(5):
            assert await faulty_func()

    await event_manager.wait_for_tasks()

    assert listener.retries == max_global_retries`

Was thinking of adding a limiter that instantiates a TokenBudgetLimiter class from hyx/ratelimit/manager.py to the RetryManager. The retry decorator can include some similar optional parameters as the ratelimit. Is this the desired functionality ? Might need some more clarification if not, thanks!

**Comment by roma-glushko** [comment]
@Chris2W 

> Appreciate it! Sorta new to open source and wanted to dive into distributed systems.

That's great, Chris! I hope Hyx will serve that purpose well 🚀 

> Would the following test be a somewhat valid usage of the retry decorator that limits the number of retries via the TokenBucketLimiter class from https://github.com/roma-glushko/hyx/blob/main/hyx/ratelimit/managers.py#L12 ?

Generally, yes 👍  A few thoughts about this test:

- the following part seems to retry until we have tokens in the bucket:

```python
with pytest.raises(RateLimitExceeded):
        for _ in range(5):
            assert await faulty_func()
```

That's fine but I suspect we may need to be able to set the per request limit (for example, 3 retries at most like in the current retry logic) as well. That is we retry until we have tokens in the bucket and at most that number of times per request. This way we could limit how many tokens one request could possibly consume from the bucket.

- Need to think if we want to raise `RateLimitExceeded` or some retry-specific error based on the underlying `RateLimitExceeded`

> The retry decorator can include some similar optional parameters as the ratelimit.

Yeah, that's a good option. Alternatively, we could have a separate specific decorator like `bucket_retry` with those specific parameters. Also, it's good to allow users to pass an instance of limiter, so users could implement their own strategies.

**Comment by Chris2W** [comment]
Interesting. I think having users to pass in an instance of a limiter might make more sense than just the parameters for the retry bucket.

As for needing to be able to set the per request limit, from my understanding, that would be including the attempts parameter, correct? I've also revised the test such that AttemptsExceeded is raised rather than RateLimitExceeded. No issues so far with that. Can discuss more in the discord! :)

**Comment by roma-glushko** [comment]
@Chris2W 

> Interesting. I think having users to pass in an instance of a limiter might make more sense than just the parameters for the retry bucket

There is a cool API design principle that sounds along the lines of "make the common case quick and easy while advanced ones possible" ([we need to sum up our design principles somewhere explicitly](https://github.com/roma-glushko/hyx/issues/80) 👀 ).

The option you have suggested Chris (e.g. having all params of the underlying token as params of the decorator) is about the common cases. I imagine most people would want to just specify those params as they use the decorator without a will to think where to put the global instance of the limiter.

The idea of passing the limiter instance is one to make the "advance" cases possible. 

But at this point it's likely not worth it to overwhelm you with such fine-grained details. We need to get the underlying logic right first, so let's focus on adding a separate decorator with all params (like you have suggested) and then we will extend that in the followup PRs/tasks.

> As for needing to be able to set the per request limit, from my understanding, that would be including the attempts parameter, correct?

Oh yeah that would make a lot of sense 👍 
We want to keep params with the same meaning/semantics called the same way across API. That should make it easy to leverage user's existing knowledge of Hyx and translate it to a new primitives they have never used before.

> I've also revised the test such that AttemptsExceeded is raised rather than RateLimitExceeded. No issues so far with that.

Great 🙌 

> Can discuss more in the discord! :)

See you there 🚀
